

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'RJB54D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'JHJ70X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'IDZ40L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'DDS14L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'TTL09Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'KBH23Q');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'LPC99H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ELD59W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'TSZ22U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ASG35W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'WNP01C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'HBC34C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'SDU09F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'NFO85U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'ILQ41N');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'JVT18Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'ZWX94I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ZAY04L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'HCY06G');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'VYY74A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'OJB52A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'FBU22B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'TXW71H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'VNV06I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'KTJ75U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'IWB78C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'LAR80A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'GRH45H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'QKQ17E');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'WQY54X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'CMF24J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'DPR89W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'AYL87P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'DJZ22S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'RDS61P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'XOE70A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'RGX90H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'MZK79Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'AZX16P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'CNU35K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'MHY74O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'DWX29M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'FMJ38N');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'QTO08J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'RXW30J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'QTN56H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'RKO98T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'SXD13X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'IPQ28A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'CLS48Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'HZY74Q');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'XGN21A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'MDR80J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'HBV74L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'RYX64O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'NZX41R');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'HCS55V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ZSZ33M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'KFS30A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'SJG31I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'ZVH11W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'LCZ90P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'APR68G');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'URK64H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'MMF86J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'QBJ08Q');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'DFD28V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'FBY29C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'KFA33M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'FJY73V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'CDU74K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ANA36T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'KQB26F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'FVM43Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'RRR05E');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'QDX22K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'XYH47X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'UVN33P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'HLO25D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'RYG00I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'HKP66G');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'YWO51T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'YCP25I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'LXD78N');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'KTK55G');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'CCL09T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'JXS72A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'FPV98J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'XPL29G');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ION67D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ULR15C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'YNQ60O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'TFG12F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'ZMP63S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'KSB79Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'KYZ62U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'EHE81B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ICP84P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'VOY00M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'FED54N');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'KQB14O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'MYX29D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'JKP09M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'RJC72X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ZQX89F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'DAO85G');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'QMQ01Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'SWP74R');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'PVX44U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'DDT31F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'CIB61H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'BGK58J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'QWO89O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ADW04C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'KWZ01L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'IGN91S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'CXM63W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'HYG19U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ZOA59X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'VDH15O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'XSY92X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'VCX90X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'UOA19I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'GYR81U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'VCE46B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'WNE99X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'RLC64L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'AAX70R');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'MOL27S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'VVF87F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'NQV94H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'AZX11V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'XSK41X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'DWY89C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'UQQ43L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'XBK87L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ZXE93F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ZOL41X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'JVP94X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'GKD18Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'YSW02O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'NRB81K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'RHG18F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'RZY61P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'UNX82V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'NSR70X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'VFG34E');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'XTL71C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'NIR38U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ODI57B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'WQE85E');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'RUX69Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'VOP99A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ASV09O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'VIZ60C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'GQV53I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'KVG72G');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'LZO30R');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'BWC72L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'HHI81J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'PWM26U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'CZT97W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'FEO33V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'ZGR73A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'WUP25I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'RVT12H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'GLB87W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'TBR84L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'DGY24L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'FAU73W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'WFK10W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'ZJC71Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'ANW36D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'LXT39L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'THJ28I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'BGD65V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'ZOU49F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'BFS46U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'VOK06X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'UJZ03E');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'SJN79C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'KJM54M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'NRT92L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'RXI49I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'EGF93A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'WYY45A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'YYI77I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'SVY92I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'QCV50C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'SLU44U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'IHP54T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'TQF98U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'LEQ86P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'FCE36A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'NIJ17O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'YYD51O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'AGD12E');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'OHL43P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'USV91D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'NNV54M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'HUS36S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'JQF11G');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'YER85Q');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'JZA34Q');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'GYY98H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'FDO26G');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'RSP93O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'DDQ42D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'OWB36A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'XHB33Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'WMY00D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'EQV28F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'NXO44O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'HFC52T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'KJP77K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'IYI67Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'BXM33T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'LME01A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'TMP21U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'CJZ81B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'HTV78X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'UEW78K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'LUN52N');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'FMT89M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'JVI62G');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'FUD84Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'ZVM40D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'TXD98L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'ZON85O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'OTY02R');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'MSA58S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'SDX48E');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'JWV40J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'UMA16Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'WGI02I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'BJW44B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'AKR79N');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'YLF20W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'EPO96B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'PKL74L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'VMZ57S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'XLJ82C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'UVP31P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'YIZ43L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'KXM73R');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'NUX48S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ENU20X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'EMK49W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ZUB25O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'XFQ08A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'XOX56L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'YDX67T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'DDQ00W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'IJK57G');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'EMY15X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'FCT06U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'FPA13T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'YRV66I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'GPC44T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'WZH43O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'KYA37K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'VTP29Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'VHC43T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'BDO99K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'XBF13V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'QGO86Q');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'QGS45I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'TPZ59H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'EMU71N');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'YBH10U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'LNC07M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'IXH14U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'OFG74U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'JHN87G');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'NAQ40C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'OFQ03S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'IZU12A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'GBS43H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'OZQ18C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ILT03Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'AWS33Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'IHG57W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'JOV51B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'IUB89W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'OYT89T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'ZRH10S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'ZBJ36I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'EUS65F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'TFK89J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'CLB54T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'TZT58K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'OIS24T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'ROS29M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'GQF85E');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'QOF94S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'CEG66K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'AAK72A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'AHB81J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'IIL95T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'VXS18K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'ABY69Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'JGJ06V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'WZE99Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'PFF10K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'RMR20C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'NTK83K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'KKP57Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'ZHU25R');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'UOR08P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'FZV24V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'JSN24I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'QTF26C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'IKA16K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'RKG41C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'SNB16T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'GRO46X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'DDK79X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'VKP21P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'MUL15Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'WPM50U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'AAO99F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ZFX32P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'GZX16F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'LEV18K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'NDF67K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'KJL40X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'KIF14S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'JVG15U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'FNO26D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'JQR40W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'XWT86G');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'DKB41H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'AXJ43B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'YYP22D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'QYB39W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'URW08E');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'GPD38K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ZGO50G');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'SMB47V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'PFO61K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'OLS69P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'VOP00U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'WFV68X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'GWP29D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'KMN89H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'XGG39D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'TJN98J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'YEM03P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'BWQ13W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'VAR67R');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'YDD12O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'YKM14Q');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'VSG89W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'NVZ73M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'XZW40D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'BGJ04V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'UEK71Q');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'KDB35O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'EIE33F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ADE25R');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'JPS24B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'TBO76H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'CRT36Q');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'KAI20R');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'TGM89Q');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'DVZ86U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'IDI96D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'RSJ76F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'UVK65T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'LLK58X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'VOZ49V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'XVU79T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'PBJ73K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'PKK50Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'DKJ96Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'DNV48C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'LYN21P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'JVC36N');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'EWS33Q');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'WCV17C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'BXY97V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'CSZ87H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'DRD70Q');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'PDB70F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'SLR90S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'RSY13K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'EQL52U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'YFF83S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'IMI61B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ONZ91Q');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'TLV56O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'YQA03V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'JNG85H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'IBW77X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'GPE35Q');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'PBJ33G');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'XVK64I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'ZPJ62E');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'QIE49F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'EDV04W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'ALK75S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'DDA47Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'CQH85T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'TMB19Q');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'NCS79L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'PCO62T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'DCJ64W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'HQD58R');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'VPE02J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ZET39H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'UBX88F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'NGA38F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'BVL30T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'XSN60A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'EFJ81B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'PKY71X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'MIY68X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'OXG52V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'DAQ83R');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'XLM99X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'PDU11E');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'HRK82S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'GKN62T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'LEV03Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'XLE44B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'RDT64Q');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'BDF87S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'VAE82T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'KVW32A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'AEB42D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'JHY43S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'XPH35L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'GDR56D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'YDJ11I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'DWJ61B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'WCP50B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'MKM04C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ASR57A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'WVX43O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'NCV39V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'OCZ84S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'IOC83K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'SIS79O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'RQH15P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'QVP98O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'JXH02M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'RCK49K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'EQP98Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'ENY33Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ETT31O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'WYX79K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'ICU88Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'MNP68E');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'OTH97V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ZPX46R');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'KHD57V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'JAI86A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'DTT91Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'JSR07P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'KPV01G');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'ENT43V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'COI44D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'ILE76S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'LPH23Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'KOZ14Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'SKB88N');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'CRJ96M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'RTK88R');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'VCD14K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'WJM75N');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'QWP69H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'TPX41D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'CJI52U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'LIO55N');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'HDL24S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'SVO95M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'WWH95N');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'CPM62U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'FNC88F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'WFX74I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'CMY68T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'JKF93U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'SJO83A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'VQQ77J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'ALV49S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'YMU60M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'FPS11B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'QVH51V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'NOF85J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'QMM84B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'JJM62Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'KJA86R');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'OSD07Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'VDU39X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'EEL71W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'AJS05E');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'CRL54J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ATL33A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'YJB37V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'YZA36B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'DAC47W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'BYD52H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'GTF04W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'SWS02Q');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'TFW53Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'RLG21N');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'GXU10I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'JYX90G');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'QLN94O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'KRV62L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'CAA98O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'SHC22C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'ITX82F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'OJQ78C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'QKC60X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'SVK41W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'RYG95Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'KMC18V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'TZF69U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'DCB36F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'JWM14J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'EQF41U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'GUH14J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'XFS73T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'EKZ44R');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'DVZ97L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'FKA09J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'XLI18O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'UHW12Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ZGA17D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'OXP26C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'DZK04T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'DYE14F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'MKM46V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'CTZ34N');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ZPG36S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'KLX55U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'NQI88K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'NGQ90D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'ULS81R');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'GSQ51S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'NXR14M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'FGR37P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'LBR49C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'LZY15R');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'UQU62A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'LSW97B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'UZA48S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'TYT12N');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'RHI34R');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'NCF90C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'BEA37H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'IVD05N');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'KCM06O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'HBH02X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'XON82T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'KRL40X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'EBA53D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'HCX54O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'RQV21V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'FUV95M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'XTH37L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'IUM82P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'WNO78U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'MYQ70U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'LTY51O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'VTN70F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'TSY91I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'TQJ99P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'LXH74Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'LGG38C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'IIZ66C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'BUS74B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'CVG57P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'KMX42V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'OLD13G');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'VBO95Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'WDO95K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'YEK91H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'DZX59E');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'FXS13X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'QCB38V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'RTN10W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'GOS06O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'GON09S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'GOC56J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'RNI63O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'JMT93Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'HNR41H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'OZX39B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'NAF12F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'GWC02M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'LSY67T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'JEO29L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'IUQ38C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'UJK11I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'LET70W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'QVA92X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ICS15Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'MWH24V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'NYD52I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'LCH94I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'GDK82T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'VJV99Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'TKU95A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'YIX81D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'ZFO20I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'IOW45K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'IBZ01F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'UVC43Q');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'OER16Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'QDN42X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'WXJ59J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'RDW33S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'FOJ82Q');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'GDW66S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'XGN49T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'MFE77R');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'BFO31W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'WEB18W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'NQR55R');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'MWP47H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'BIE46O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'EPU24P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'RNB57U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'KJW38F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'LKF63P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'IPY06E');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'IMA34T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'YZP27Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'APS41N');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'FDA11Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'NRY58J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ZIL19D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'UQS30K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'EAG80H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'AAZ20J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'BDZ51Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'AHB50W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'IJM82L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'WDE34V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'TSA00C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'AHX99S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'GAT69I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'HOD86F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'GWK56Q');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'SXF49J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'CLI05W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'FAR62V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'GBV79I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'LJQ16H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'RJW57P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'UML47K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'OZS66N');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'JRU25F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'PUG43U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'XGZ00L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'UWJ10Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'XYT96Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'CDC93J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'RCQ05A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'AME89T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'MPR79M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'TJG29H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'HGZ28M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'VBW87G');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'XLU05C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'XRB88T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'WCV05W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'FWQ46L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'JMZ45I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'EQT34H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'GEI32W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'DDE17N');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'VMQ49E');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'NKD58T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'NIN98X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'RIR36Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'XCB27C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'MKK93Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'OLY83B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'MZC11Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'TAP05B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'IXT72H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'OXM18G');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'HQM85Q');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'WMX64A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'KCU88N');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'HRQ76K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'JWJ70A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'WDJ93I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'VGU69L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'FIH15B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'QFQ89H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'KOQ97N');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'LRV68T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'VUX64H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'BYU59N');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'QZA08C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'GCX61E');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'GPY53D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'GKJ61D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'JHZ76O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'FOH92S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'TQF14V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'MEU11H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'XXK87P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'YSY14X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'JCW92Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'UJU62Q');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'SMU32R');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'QGJ00P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'IUL17M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'MCY67M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'VJT29E');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'GJS14H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'NWM92X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'TRU21T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'AKW60I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'PMN36P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'QOS26R');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'LOS89C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'SBT27N');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'CDA57P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'LJW08J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'NMQ77F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'CNB10K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'JQG25H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'LPV06E');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ROI67C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'INJ49S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'FZY92F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'CCM31Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'JWK98Q');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'CBK93I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'YGI70A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'SYG58G');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'RAT10S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'CDI87M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'IHF82I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'GYT83V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'WQP40U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'TUN88Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'WNW89Q');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'AWK98H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'SPW22V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'WHK94W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'SOQ19N');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'NPO31Q');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'ODZ62Q');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'NYK54P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'FRD59D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'IIS72H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'TGE04V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'YUC14T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'NJA06P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'GAU93F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'IHO33W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'UCA48J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'IIZ54E');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'DPV98Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'UME65S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'TDC23H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'OGJ21T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'FFR54P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'GBV75D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'EBX69W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'LQM29P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'OTD14E');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'FIX28X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'CCN98D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'OOB64J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'TOG08S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'WQP87X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'UOB11O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'XGA89U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'DWD71M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'NHA22J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'FNB63T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'HXC02D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'SKY03Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'VBS77X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'OLA95H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'OGP04O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'QCL34J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'OPS86W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'DIB52V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'FLP43V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'YLG57H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'LEF00R');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'SAZ56G');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'CKH67Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'TFR77D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ANO03X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'REE91N');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'BVT95B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'ZDP86H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'ZUC81F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'RZQ67T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'LBA20X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'KDG13H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ETQ69L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'VMA49V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'VVI64E');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'OLO35F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'DWB24P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'XGE04L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'WKF21B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'KXJ51P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'NXZ92Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'BID74Q');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'KSV83A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'PKO39P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'DZD54T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'FKY64Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'UAV52W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'NLW60O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'LBM35X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'EAF66H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'BMK18L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'MPQ62Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'BKP47J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'NFK16H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'KAX31L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'RYC86E');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ACU86Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'KXQ63Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'MSA81Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'HZN62T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'TQT08Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'FWY76N');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'FHO09C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'EER45M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'RBB33J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'YBR09F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'DUI92M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'AWT97N');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'EAQ62G');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'YCC53T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'YIG21X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'YMD57U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'EVY38S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'PUE85I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'PQR51X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'GHX45Q');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'NTU65P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'YKX48R');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'YCQ65L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'UKD22P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'BTZ51U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'JYA80O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'LFB63X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'TIX28B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'EPI90F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'IER76D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'BRW35Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'XVO73R');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'KJO82F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'IWB93G');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'MQU82R');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'GZE11L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'KHP17T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'IVX43U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'JEA39Z');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'SZG15C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'LST42P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'QRC39M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'MVV54X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'VSS87T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'QQG20M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'PIO50R');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'WAO17Q');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'RGM79Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'UPF22A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'JMA98M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'DLA75G');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'IXK59E');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'HVI95W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'YAW02S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'HMF07X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'RSR51X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'CXX30A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'TXI29Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'CQU52K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'XQO39D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ERJ21D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ENR55H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'PNH60I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ODI90L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'QOI80Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'WEA15Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'VGT38I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'FIQ80T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'EAV68M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'RAD06D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'GVH08L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'GVQ39M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'SXD05V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'NTY45K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'PFM77B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'FRY28W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'RHX50J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'XYD05P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'FMV06L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'SAS62R');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ZXW19Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ERB86K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'BTB20J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'EDL42C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'YRO74Q');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'WMM28F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'VVV47L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'WEU88F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'OMH14X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'MCT15P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'XJS39W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'AFF72X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'MHZ94H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'URE44G');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'AKC41L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ZMW46E');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'USW41U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'OJI15R');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'CPA63E');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'FVK92V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'XSJ19M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'KTR11I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'DWG71K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'OYV55K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'QJO74L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'KJS97R');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'VYE81Q');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'LEA24L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'VOA54Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'LBM18E');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'XLI09B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'YCU68N');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'PJB60T');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'QII80O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'DGE53X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'XCD62E');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'UDO67M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'ZVP90M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'RUT21F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'KVG53U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'IOU42N');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'LSO26A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'FPE11U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'VUU35Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'RTW65K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'DOO71B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'VDP51N');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'PRZ10C');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ISE41O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'ZJI40U');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'MZV44S');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'BHW11O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'DHZ93H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'PFY14L');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'KMM05B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'TMK83Q');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'IGF08D');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'GZR01W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'RQY90O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'CCI94H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'GAJ55J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'IQG66H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'OKG83K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'XRP34J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'XCX44B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'OCK96K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'WFD56B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'EHE50W');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'LHT25Q');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'GTD21V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'NHN47A');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'NCL93M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'CTI30F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'PGB15J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'PHV84M');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'LGN70E');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'KIX82K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'JLL81Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'GOW11X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'GND48P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'BQD45F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'QGP86B');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'AYN83G');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'LLN04I');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'FRF37H');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'DJD84O');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'LUT64P');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('125', 'BSB63F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'CFN72V');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('200', 'DTA14K');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('300', 'OZJ12Y');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('350', 'JYG33F');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'XUC06X');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'CMN73J');

INSERT INTO MOTOS (TIPOCILINDRAJE, IDVEHICULO) 
VALUES ('150', 'RRB02S');

