

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'HGN180');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'AIO343');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KTZ091');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CMV448');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'POJ300');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CQX708');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BTI037');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PIA918');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'VSN621');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JGG575');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UMD847');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CMV936');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'AJC782');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'IIG808');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CZS590');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'NAK918');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PZP623');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QFA022');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RUI629');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'HFX127');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TBM006');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'EXF690');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'LVS062');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BXE370');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'HER596');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'YRU715');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FEB424');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RUM978');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (2, 'TZO297');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UJN634');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QWD345');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'LSH949');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RES728');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CRQ663');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KEP848');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BTX814');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DXP042');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XAT120');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ORM902');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'EOO561');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZMK164');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BAF319');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QWT180');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XQF372');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'HNR834');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'NOY673');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'EEC035');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FHD083');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'HGI020');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'LMW664');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TJU061');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KZY158');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'VBW907');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'AXT774');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ESL465');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XPR501');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'EUX095');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (2, 'RRK581');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RLJ182');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZZO211');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QAO048');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TTD897');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RUH341');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OEQ224');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WEK986');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SWS419');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XST316');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MXU957');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JPT087');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'VFF531');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PIZ474');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KUB247');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CYQ139');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TTD657');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QFQ857');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PUU705');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'LNM812');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DQU081');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'EWC036');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CBJ477');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UZQ745');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RGI456');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'THV963');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PFS157');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DWD213');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XTJ205');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (2, 'BOR891');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CLX136');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GMH054');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'VEU351');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ICL047');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ROK215');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'HBH901');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'APJ928');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'YBX751');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RGU176');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MOE592');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'EBL155');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WUZ561');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GNS531');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RZI325');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GKR892');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GEL811');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'USJ769');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TVB652');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PYM382');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WJP988');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OBR633');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TNS915');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TLI269');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CSW781');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RSP803');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XKM260');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XII851');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BPO119');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (2, 'JYC994');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'NPJ300');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FFT896');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'YIZ237');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MFY067');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ITI394');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RHV410');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'AGM811');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UAP614');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'LIC697');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'THB800');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ION828');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'IMU120');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'LIR502');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'VFA383');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UPQ680');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DST108');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MFG054');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MSN682');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'HVY902');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'VSG021');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QRR059');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TAA511');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'EZL921');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XIH094');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PEP845');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'LBB688');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'YQC302');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KCW450');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (2, 'QIH059');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UYT974');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CYY269');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WRE865');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'AVS049');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UBA475');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TUT002');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QGK563');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZRF934');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TXO843');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RJB303');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RGQ572');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'EZV496');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ERR257');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DGX435');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UVE282');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MWV316');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WRP622');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MUO109');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JLN561');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'VTY520');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UFZ419');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JCW832');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FAN850');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'AEY873');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SYP533');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GYX353');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GCS044');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MAK952');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (2, 'FDI495');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'LUV583');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RKN102');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KJV553');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OKY126');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TTC354');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MYO953');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FPI187');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CBY525');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GZM529');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WOF151');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'IKI629');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'APM534');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TJC092');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZXB630');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WCX398');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DHL220');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'HZE671');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SGZ562');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XGR898');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DGX510');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FYZ440');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WDV916');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'YUU201');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ANU522');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KGS644');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'NQU557');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JJA652');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BCB749');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (2, 'UHK337');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (2, 'ALS971');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (2, 'FCQ791');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QHQ398');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MOT242');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'IEX077');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WFO937');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'HGZ482');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CWA794');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'APC681');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'HDH792');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MVV538');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CTJ245');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UCD971');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OEW493');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TZK325');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GQR163');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'EHX349');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZQJ541');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'YGZ249');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FMX544');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (2, 'DCP265');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (2, 'DPP570');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BGP276');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KQF553');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'YMY450');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UMH365');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JBL174');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OVP424');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'NWS437');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MVJ801');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'YDX296');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (2, 'IHR277');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (2, 'NEC332');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (2, 'XJN319');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (2, 'HYH208');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PJV494');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'NRE694');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CLD606');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'EGU038');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'NTK257');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (2, 'HWX321');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (2, 'LLC872');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (2, 'HOA834');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (2, 'NIN138');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (2, 'BPT958');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ISN968');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZXF109');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZGS661');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MML990');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BDV910');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'YTM869');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SFH133');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'LST091');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OMV516');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MXT406');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GOA099');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KKJ711');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XLS460');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SUN786');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KKG109');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'LYD414');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UNU876');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JHD053');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'AQB867');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WEK713');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KFL566');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UHS218');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OND712');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KTT501');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'YMU203');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'YAH441');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GHM696');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KMG506');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'EWK057');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZLF449');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XPQ388');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XDM749');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'HLZ802');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'AWA944');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QWL750');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'HDD121');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FWJ012');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TEF671');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XFL119');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BRO903');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZCA136');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CVE693');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XYF003');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BPW011');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GZB951');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BEN695');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DOZ109');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CYR840');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XCF313');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JLN275');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'IPB842');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MFB314');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SKB902');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'HUE283');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'USL351');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZOV304');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FKM646');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'AWC256');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KCS180');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZYW413');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QNO506');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PFL276');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UYU958');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KLY485');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PPN483');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'EFH992');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SAS848');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'IQK298');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'AIE093');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DDO559');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FXR355');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ICF894');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OZF942');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BTT492');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CKM106');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QPF373');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FNV205');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CUM677');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QEJ767');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'YOJ309');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ETJ545');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WGA496');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ACT954');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'LPF013');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GJI016');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DBK258');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'IZX249');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TZM403');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PXH056');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ATD272');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JCV448');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZAG936');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PUE878');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BDF033');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'IAZ804');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'EHG333');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ITM200');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZRH359');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'VRL172');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JJV325');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FPE089');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QDI637');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SSH346');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JIL032');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'LIH459');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UGF298');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OLW138');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JCS080');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CBU726');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PZN338');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SXX691');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TCQ011');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'EOW627');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UEM045');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OWG454');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GID516');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'IMI037');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KLR910');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KTG071');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ELZ209');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'YSV712');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FRC789');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CYR897');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MHY065');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BOG688');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GOB669');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'YZS458');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QSH225');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'HEL151');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SQR819');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ALG989');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JVK473');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XGZ245');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KXL878');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DOH170');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'LKF316');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UJV475');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'HOK026');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'URF161');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CWL391');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GYH408');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TCL892');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SQB377');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'EOJ321');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FIZ678');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'YVD078');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SLS034');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PUF601');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'LJH408');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GVW666');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XIQ668');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MMS357');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'IDQ033');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GOO796');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WLH776');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'LSY979');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RVS476');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WCH703');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'LSZ487');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MGP091');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PPM515');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'NLY505');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'HZH957');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XOE884');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ESG530');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'HOY044');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FMX245');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'IEW566');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ABM148');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CCP578');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DQA593');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XHB732');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PEW919');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'STO072');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GDD812');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'STV954');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JHP588');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'YSX719');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'NUP521');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JJH511');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RWA607');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CMF911');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'VNA525');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CUP855');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'VVQ773');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MAI557');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'AAY371');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'COL817');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZGJ847');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GEC945');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SQM978');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'USF040');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'YYK489');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'LWI243');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JZA358');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TWW291');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GHR435');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'IMV967');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XXC306');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WHG390');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'LJX960');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DVU415');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CHM267');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WFH053');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KPF563');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'YVT088');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FSV137');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RSU789');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ADJ782');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'IXT685');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'VLB389');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TRC820');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SYI741');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'NMP701');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PEA014');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MCH002');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MPY027');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SYO187');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZFQ846');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OGF788');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'NZG525');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ALG492');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TTR522');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'LEP116');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KKQ362');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JTE842');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZVC272');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XDN233');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DZU455');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XGB114');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DEP520');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'AXP707');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WPD289');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GRN555');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MOG901');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'IXP113');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QMU480');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'IPH048');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PLE835');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'IOP226');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FTA237');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RER488');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZDZ586');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CEE909');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PYW522');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QGY738');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JLB291');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SXO242');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KBQ364');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZWC445');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UJF980');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'LBQ344');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WWI110');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DOS331');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OGC455');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'HRJ021');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CSZ670');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TBW897');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XSE239');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MZT395');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DXL219');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'VDV968');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'IDS585');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BCT552');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FGV344');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BLF448');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SCQ010');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PMU306');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZHS331');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XEQ632');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JKO560');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OZK894');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QKJ498');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'LGP963');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QMZ069');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'EJU761');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FOD098');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'YFS188');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XTM967');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RFM227');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MID104');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PMO043');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TQR156');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'VVN838');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'EZA841');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DJU283');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BPB505');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WFU955');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KEO225');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZLH680');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QLK717');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DKW882');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SXA115');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MLH263');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TSM969');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OWG094');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QTD541');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KRZ001');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WLV924');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TIO937');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'LSC224');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TUW610');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XSR064');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TJW014');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'NWJ298');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GZY066');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BFG789');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RVA512');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WQX065');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'VEA853');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MNV217');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZFA252');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KUR185');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MHH919');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UXZ589');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZVB027');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BMT687');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PST168');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'NRX064');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RZJ640');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DXU320');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ARP711');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KAX425');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QGR012');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ULK037');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DCN113');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BQB763');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FLW228');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'VLF179');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FSC368');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OTS582');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'EWE611');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DNY524');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BXY413');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'NOG779');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RFX380');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RAO127');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CLF227');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SFK279');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GXY873');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZZO131');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WXO976');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TUR958');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'YXN631');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DSJ995');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'NEE505');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OVA746');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BTK644');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QZY493');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BZU257');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'IYB579');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OZC949');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WXM475');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TGW200');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BUX662');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FCN993');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'IXW194');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PVL342');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BFZ492');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'NUW253');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JIO560');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FEP766');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ESC938');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JAF787');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'THO349');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OUI698');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BDQ692');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WDP624');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'NST963');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JSZ444');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'AVL530');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KHO816');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SGD578');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TWQ177');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TCF656');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'IZI803');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TAH678');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BOU986');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JZE110');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CHN940');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OYE726');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'IZK507');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UGF755');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GKI126');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KCK427');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZZV978');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GGG183');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BTO028');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RXA799');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'LRE233');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CTC402');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JDO852');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MZR079');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QPV625');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XJK439');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GXM500');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZEY135');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MOM778');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'IZJ597');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'IGM124');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'NGG209');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PAP417');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WFV683');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BEU845');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'NOR026');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TXQ849');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'IAP250');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'EVL660');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JZX575');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BFC833');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZKS873');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JAN639');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KVR029');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RGS057');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZGV608');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QYZ229');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'VYW680');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PZK457');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QTQ710');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'YLO508');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PHH443');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QMN186');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'NWY121');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SYJ606');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'VSY342');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KRV200');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SAY987');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'YOD999');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ONA602');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'IBO203');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DLI781');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TPM502');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XWW888');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OUV830');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UNM155');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SHF143');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QOS210');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PFW407');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JUD330');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PEV976');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FZV232');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SAR665');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DFG524');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QUF375');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'LLB860');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'VJI574');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ELF391');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UPR712');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'HDS714');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'THO100');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CEC954');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FJQ619');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QFM843');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'COH946');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FSU647');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'AEN458');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ELZ747');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TMX358');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FVL568');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UPZ403');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WPH559');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'AVK624');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OWG246');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FVD982');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QQJ751');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DAV319');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OXN120');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'LDC663');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'THB908');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SBA829');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KTL931');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'INM612');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DQL992');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DJS988');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ERK730');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'IZA948');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'YSS699');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MCO171');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'EVQ614');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DYD329');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FES827');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PFU179');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RSP862');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SRL451');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZMH838');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'VBA843');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DRW345');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TDD548');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'LUU214');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'YOJ320');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OOO508');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SZG475');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZET875');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UHU326');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'NHG140');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BPP712');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZPA454');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'HJM325');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'EHM078');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OPO821');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RZC872');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TGY060');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'VGM017');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BTZ956');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CVO982');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MCG878');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UZN221');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TDP030');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'HQJ644');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'IPK467');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CRS662');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GWY353');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FUN157');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FAE142');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WCG498');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GSQ125');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FRS881');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'LKM851');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BEQ899');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TBX060');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'AIW758');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RTD258');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QKS319');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KPA349');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QSC382');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RDR596');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QEF026');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QMO520');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'LWD977');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JLI673');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KPS121');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TEB754');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UFK614');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MDQ135');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OAT189');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XVH848');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'EOC990');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZXS217');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WQS711');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PLT301');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DOC378');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BUS333');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'LCS763');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CZY608');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'VSN438');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'HEP484');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MUW371');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RCX468');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OPI581');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'AOI063');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'IRU753');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'EUN633');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'HJI447');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'EUM646');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XZA806');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'IOV199');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MYL859');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MAO012');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'YSA205');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CSN069');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CXJ286');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'URG203');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RZT841');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RKN003');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BPS461');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FWK734');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'EPP170');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QLJ256');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SVJ731');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UBV452');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'NWI434');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WYF873');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ASM756');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UVW758');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CMK948');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'YWG047');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TVJ216');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DYQ715');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FOG290');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RGT200');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RXM250');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PHJ794');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KTG708');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BTX637');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KNY947');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PIR469');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RWA007');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OND637');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RNG712');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MCY270');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DYS712');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'HEV504');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JKO221');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PXB491');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MYO731');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QRZ837');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BJP232');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WSN246');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DBJ417');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'NML614');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'HGR326');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'EYC727');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SNI732');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JTE717');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BAE775');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'IPK230');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MLW584');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DOP153');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RRS155');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZRX333');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FLZ902');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'YHS615');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ERB490');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DRF594');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'EJH569');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JFV761');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'IYT073');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZOO179');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'HFC022');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SNF252');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GHK616');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JKK853');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZRS358');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XNF423');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'LIC255');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'HQO972');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JLM725');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UEI999');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'URG993');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OOJ954');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ELZ707');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WWS869');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MYI336');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GXK695');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'VRE941');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'COU427');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'LNQ179');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'LST493');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GXG924');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'VTN044');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XHG639');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WLW417');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KWR174');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SBO656');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OPJ392');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PMC441');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'NFG002');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FMI707');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'HZG081');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SZW483');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'YZD102');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MHM130');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CFP318');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OQJ952');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FVQ644');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BXJ211');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ILU008');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'EDX590');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TJN887');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JRK626');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CTU225');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DLL766');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'HVC145');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OCW569');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OBZ257');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SPJ113');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'NGO927');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'VUF740');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XDX590');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'PKL357');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CRW786');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BDN963');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QNB827');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QZA708');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'XPN950');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WFK399');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KXA816');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ACT337');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UQQ737');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QKN089');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZRW515');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DNE701');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GFE281');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KXX001');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QUR138');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MWS417');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QWK891');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ROI630');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UKK472');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'HGC470');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QTU764');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JRT718');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UMC994');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RKU449');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MPM220');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SVW016');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'AZN575');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UHS211');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'YRE812');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UTC317');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DXY528');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZCP991');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KZO586');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'NYZ663');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JGD705');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'QKZ132');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OWT308');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GIO487');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MUX364');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'YIN443');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'UPG416');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'HNH798');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JNW077');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'GTA363');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'YIQ308');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SFB588');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'AXO211');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ETZ237');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'BHF375');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'CNQ796');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WBS473');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'HIC000');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'TQE025');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'NKV186');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ALS672');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WMB842');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'KBB444');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'URF976');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MBS631');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'NBU651');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'SFI269');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OPT159');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'MDE108');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'YSO086');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ELM907');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RCG115');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'DTN330');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZUR301');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (2, 'UPV718');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (2, 'NLC198');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'JCU733');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'LLS712');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'FQM062');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'HQL496');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (2, 'HOA858');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'RNP038');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (2, 'OWT065');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OCB114');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'OAG677');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (2, 'PET765');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'ZTC967');

INSERT INTO AUTOS (NUMEROPUERTAS, IDVEHICULO) 
VALUES (4, 'WAI028');

