CREATE ROLE Pasajero;
CREATE ROLE Conductor;
CREATE ROLE Administradoress;

GRANT EXECUTE ON PA_PASAJEROS TO Pasajero;
GRANT EXECUTE ON PA_ADMINISTRADORES TO Administradoress;
GRANT EXECUTE ON PA_CONDUCTORES TO Conductor;