
/*XTablas*/

DROP TABLE Usuarios CASCADE CONSTRAINTS;
DROP TABLE Pasajeros CASCADE CONSTRAINTS;
DROP TABLE Conductores CASCADE CONSTRAINTS;
DROP TABLE Verificaciones CASCADE CONSTRAINTS;
DROP TABLE Calificaciones CASCADE CONSTRAINTS;
DROP TABLE Vehiculos CASCADE CONSTRAINTS;
DROP TABLE Autos CASCADE CONSTRAINTS;
DROP TABLE Motos CASCADE CONSTRAINTS;
DROP TABLE Recorridos CASCADE CONSTRAINTS;
DROP TABLE Horarios CASCADE CONSTRAINTS;
DROP TABLE PuntosDeRecogida CASCADE CONSTRAINTS;   
DROP TABLE Ubicaciones CASCADE CONSTRAINTS;
DROP TABLE Viajes CASCADE CONSTRAINTS;         
DROP TABLE Multas CASCADE CONSTRAINTS;
DROP TABLE Pagos CASCADE CONSTRAINTS;
DROP TABLE Reportes CASCADE CONSTRAINTS;
DROP TABLE Notificaciones CASCADE CONSTRAINTS;

